### ISSUE TITLE
Unable to Implement Angular Animations in Storybook

### ISSUE THREAD

**Issue by Thyregod** [brandonroberts/analog-angular-storybook-v16#1]
**Description:**
When attempting to integrate an Angular Animation into a component and running Storybook, I encounter an error in the console.

**Question:**
I'm uncertain whether I've configured the Angular Animation and Storybook integration correctly. Am I missing any specific configuration steps or settings that could be causing this issue?

The error looks like this:
<img width="692" alt="image" src="https://github.com/brandonroberts/analog-angular-storybook-v16/assets/22339038/545d0263-f9e7-496c-816d-ba9f5b9c2bb3">

**How to reproduce:**
1. Add the code as described below
2. Run `npm run storybook`
3. Open the button story
4. See the error in the console

```ts
// .storybook/preview.ts

import { type Preview } from '@storybook/angular';
import { applicationConfig } from '@storybook/angular';
import { provideAnimations } from '@angular/platform-browser/animations';

const preview: Preview = {
  ...
  decorators: [
    applicationConfig({
      providers: [provideAnimations()],
    }),
  ],
};

export default preview;
```

```ts
// src/stories/button.component.ts

...
@Component({
  selector: 'storybook-button',
  standalone: true,
  imports: [CommonModule],
  animations: [
    // Define animation
    trigger('enterAnimation', [
      transition(':enter', [
        style({ background: 'transparent' }),
        animate('500ms', style({ background: 'red' })),
      ]),
    ]),
  ],
  // Use animation
  template: ` <button @enterAnimation ... >
    {{ label }}
  </button>`,
  styleUrls: ['./button.css'],
})
...
```

**Comment by brandonroberts** [comment]
There was a bit more configuration needed to compile the TypeScript files in the `.storybook` folder. 

I added the changes here https://github.com/brandonroberts/analog-angular-storybook-v16/commit/b5ea55b41e0dd60bc4047477ee028688eee37e49
